### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yjun123**
Hi, I have submitted Neeto-Vue to [AUR](https://aur.archlinux.org/packages/neeto-vue-bin/).
Arch Linux user could install and upgrade Neeto-Vue with a very simple way.

image

thank you for your work.

### CODE REVIEW

**Comment by TankNee** [comment]
Thanks for your excellent work !
I want to know what I need to do if I want to maintain this source on arch Linux ?

**Comment by yjun123** [comment]
No, there is nothing to do for you with AUR.
When Neeto-Vue have a new release on github, I will update the PKGBUILD of Neeto-Vue, the Arch Linux package script, on AUR.  
Arch Linux users could get upgrade just type a simple comand `yay -Syu`, it  automatically executes downlaoding, checking integrity, packaging , installation.   that's all.

**Comment by TankNee** [comment]
thanks, that's brilliant.

**Comment by TankNee** [comment]
@yjun123 
Hi, recently I have released new version of Neeto-Vue which has renamed to Memocast, maybe you can upgrade the package of Memocast(Neeto-Vue) that uploaded in AUR?

**Comment by yjun123** [comment]
https://aur.archlinux.org/packages/memocast-bin/

**Comment by TankNee** [comment]
thanks

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："yjun ***@***.***&gt;;
发送时间：2021年8月28日(星期六) 中午12:38
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [TankNee/Memocast] Update README.md (#54)
-----------------------------------

 

 
https://aur.archlinux.org/packages/memocast-bin/
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
